=== AI-Unleashed/GPT4o_Vision/invoice_schema.json
{
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "title": "Invoice",
  "description": "A simple invoice format",
  "type": "object",
  "properties": {
    "invoiceNumber": {
      "description": "The unique identifier for the invoice.",
      "type": "string"
    },
    "dateIssued": {
      "description": "The date when the invoice was issued.",
      "type": "string",
      "format": "date"
    },
    "dueDate": {
      "description": "The date by which the invoice should be paid.",
      "type": "string",
      "format": "date"
    },
    "from": {
      "description": "Information about the issuer of the invoice.",
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "address": { "type": "string" }
      },
      "required": ["name", "address"]
    },
    "to": {
      "description": "Information about the recipient of the invoice.",
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "address": { "type": "string" }
      },
      "required": ["name", "address"]
    },
    "items": {
      "type": "array",
      "description": "List of items included in the invoice.",
      "items": {
        "type": "object",
        "properties": {
          "description": { "type": "string" },
          "quantity": { "type": "number" },
          "price": { "type": "number" }
        },
        "required": ["description", "quantity", "price"]
      }
    },
    "total": {
      "description": "Total amount of the invoice.",
      "type": "number"
    }
  },
  "required": ["invoiceNumber", "dateIssued", "from", "to", "items", "total"]
}

=== AI-Unleashed/GPT4o_Vision/Sample-Invoice-printable.json
{
    "invoiceNumber": "#INV02081",
    "dateIssued": "2018-11-11",
    "dueDate": "2018-12-01",
    "from": {
        "name": "Stanford Plumbing & Heating",
        "address": "123 Madison drive, Seattle, WA, 7829Q"
    },
    "to": {
        "name": "Allen Smith",
        "address": "87 Private st, Seattle, WA",
        "email": "allen@gmail.com",
        "phone": "990-302-1898"
    },
    "items": [
        {
            "description": "Installed new kitchen sink (hours)",
            "quantity": 3,
            "price": 50.0
        },
        {
            "description": "Toto sink",
            "quantity": 1,
            "price": 500.0
        },
        {
            "description": "Worcester greenstar magnetic system filter",
            "quantity": 1,
            "price": 190.0
        },
        {
            "description": "Nest smart thermostat",
            "quantity": 1,
            "price": 250.0
        },
        {
            "description": "Worcester Greenstar 30i",
            "quantity": 1,
            "price": 1500.0
        }
    ],
    "total": 2844.8
}

=== AI-Unleashed/GPT4o_Vision/image.json
{
    "invoiceNumber": "74322107",
    "dateIssued": "2016-02-02",
    "from": {
        "name": "Davis-Obrien",
        "address": "736 Derek Station Suite 883, New Laura, WA 77568"
    },
    "to": {
        "name": "Taylor Ltd",
        "address": "213 Thomas Vista, East Zacharyshire, WI 95033"
    },
    "items": [
        {
            "description": "100cm Nordic Round Area Rug Abstract Geometric Patterns Non-Slip Floor Carpet",
            "quantity": 2.0,
            "price": 30.98
        }
    ],
    "total": 61.96
}
